export const EVENTS_DATA = [
  {
    id: "evt-1",
    title: "Intro to Next.js & React",
    date: "Oct 15, 2026",
    time: "5:00 PM - 7:00 PM",
    location: "Lab 3, Academic Block",
    description: "Learn the fundamentals of building modern web applications using React and the Next.js framework.",
    type: "Upcoming",
    category: "Workshop",
    color: "cyan",
  },
  {
    id: "evt-2",
    title: "CODE BLACK Hackathon",
    date: "Nov 01 - Nov 03, 2026",
    time: "48 Hours",
    location: "Auditorium",
    description: "Our flagship 48-hour hackathon. Build innovative solutions, win prizes, and network with industry leaders.",
    type: "Upcoming",
    category: "Hackathon",
    color: "pink",
  },
  {
    id: "evt-3",
    title: "Git & Open Source",
    date: "Sep 20, 2026",
    time: "6:00 PM",
    location: "Virtual (Discord)",
    description: "A beginner-friendly session on version control, GitHub workflows, and how to make your first open source contribution.",
    type: "Past",
    category: "Seminar",
    color: "yellow",
  },
  {
    id: "evt-4",
    title: "AI & Machine Learning 101",
    date: "Aug 10, 2026",
    time: "4:00 PM",
    location: "Seminar Hall",
    description: "Demystifying AI. We covered the basics of neural networks, model training, and how to get started with TensorFlow.",
    type: "Past",
    category: "Workshop",
    color: "purple",
  }
];
